add flow.ci
ligurio/awesome-ci pull request #105
Opened 2021-02-26 22:10 UTC by gy2006

2021-02-26 23:04 UTC, ligurio requested changes
Typo

2021-02-27 08:16 UTC, gy2006 commented
> Typo in "Availabilty"

fixed, thanks 👍

2021-02-28 06:48 UTC, ligurio commented
squash commits please

2021-02-28 14:27 UTC, gy2006 commented
> squash commits please

done

2021-02-28 15:56 UTC, merged

2021-02-28 15:56 UTC, ligurio commented
Thanks!